WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact')
]

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Введите жанр книги",
                            verbose_name="Жанр книги")
    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите язык книги",
                            verbose_name="Язык книги")
    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите наименование издательства",
                            verbose_name="Издательство")
    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100,
                            help_text="Введите имя автора",
                            verbose_name="Имя автора")

    last_name = models.CharField(max_length=20,
                            help_text="Введите фамилию автора",
                            verbose_name="Фамилия автора")

    date_of_birth = models.DateField(help_text="Введите дату рождения",
                                     verbose_name="Дата рождения",
                                     null=True,
                                     blank=True)

    about = models.TextField(help_text="Введите сведения об авторе",
                             verbose_name="Сведения об авторе")

    photo = models.ImageField(upload_to='images',
                              help_text="Загрузите фото автора",
                              verbose_name="Фото автора",
                              null=True,
                              blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Введите названия книги",
                             verbose_name="Название книги")

    genre = models.ForeignKey('Genre',
                              on_delete=models.CASCADE,
                              help_text="Выберите жанр книги",
                              verbose_name="Жанр книги", null=True)

    language = models.ForeignKey('Language',
                              on_delete=models.CASCADE,
                              help_text="Выберите язык книги",
                              verbose_name="Язык книги", null=True)
    publisher = models.ForeignKey('Publisher',
                              on_delete=models.CASCADE,
                              help_text="Выберите издательство",
                              verbose_name="Издательство", null=True)
    year = models.CharField(max_length=4,
                            help_text="Введите год издания",
                            verbose_name="Год издания")

    author = models.ManyToManyField("Author",
                                    help_text="Выберите автора(авторов) книги",
                                    verbose_name="Автор (авторы) книги")

    summary = models.TextField(max_length=1000,
                               help_text="Введите краткое описание книги",
                               verbose_name="Описание книги")

    isbn = models.CharField(max_length=13,
                            help_text="Должно содержать 13 символов",
                            verbose_name="ISBN книги")

    price = models.DecimalField(decimal_places=2,
                                max_digits=7,
                                help_text="Укажите стоимость книги",
                                verbose_name="Цена книги")

    photo = models.ImageField(upload_to='images', help_text='Введите изображение обложки',
                              verbose_name="Обложка", null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in self.author.all()])
    display_author.short_description = "Авторы"


class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус книги",
                            verbose_name="Статус")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
    book = models.ForeignKey('Book',
                             on_delete=models.CASCADE,
                             null=True)
    inv_num = models.CharField(max_length=20,
                               null=True,
                               help_text="Введите инвентарный номер книги",
                               verbose_name="Инвентарный номер")
    status = models.ForeignKey('Status',
                               on_delete=models.CASCADE,
                               null=True,
                               help_text="Изменить состояние экземпляра",
                               verbose_name="Статус экземпляра книги")
    due_back = models.DateField(null=True,
                                blank=True,
                                help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания статуса")

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        return '%s %s %s' % (self.inv_num, self.book, self.status)

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from .models import Book, Author, BookInstance
from django.views.generic import ListView, DetailView
# Create your views here.

class AuthorDetailView(DetailView):
    model = Author
    context_object_name = 'author'

class AuthorListView(ListView):
    model = Author
    paginate_by = 4


class BookDetailView(DetailView):
        model = Book
        context_object_name = 'book'

class BookListView(ListView):
    model = Book
    context_object_name = 'books'
    paginate_by = 3
def index(request):
    text_head = "You can get e books on this site"
    books = Book.objects.all()
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status=2).count
    authors = Author.objects
    num_authors = Author.objects.count()
    #text_body = "Body of main page"
    context = {'text_head': text_head, 'books': books,
               'num_books': num_books, 'num_instances': num_instances,
               'num_instances_available': num_instances_available,
               'authors':authors, 'num_authors': num_authors}
    return render(request, 'catalog/index.html', context)

def about(request):
    text_head = "Data about company"
    name = "World of books"
    context = {'text_head': text_head, 'name': name}
    return render(request, 'catalog/about.html', context)


def contact(request):
    text_head = "Contacts"
    name = "IP Tsokalov"
    address = "Serova 4/1"
    tel = "8-928-338-29-98"
    email = "tsokalov1994@gmail.com"

    context = {'text_head': text_head, 'name': name, 'address': address, 'tel': tel, 'email': email }
    return render(request, 'catalog/contact.html', context)

templates/catalog/about.html
{% extends 'catalog/base.html' %}
<head>
    {% load static %}
</head>
{% block content %}
<div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="d-flex justify-content-center align-items-center" style="height: 300px; background-color: #dbb781;">
            <img src="{% static 'images/anna.jpg' %}"
                 style="max-height: 300px; width: auto;" class="d-block"
                 alt="image">
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Some representative placeholder content for the first slide.</p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="d-flex justify-content-center align-items-center" style="height: 300px; background-color: #dbb781;">
            <img src="{% static 'images/Tolstoy.jpg' %}"
                 style="max-height: 300px; width: auto;" class="d-block"
                 alt="image">
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Some representative placeholder content for the first slide.</p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="d-flex justify-content-center align-items-center" style="height: 300px; background-color: #dbb781;">
            <img src="{% static 'images/pushkin.jfif' %}"
                 style="max-height: 300px; width: auto;" class="d-block"
                 alt="image">
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Some representative placeholder content for the first slide.</p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

    <div class="container-fluid">
      <h4 class="text-center">{{text_head}}</h4>
    </div>
      <div class="row my-2 text-center">
        <div class="col-3"></div>
        <div class="col-6 text-center">
          <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Accordion Item #1
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <strong>This is the first item's accordion body.</strong> It is shown by default, until the
                  collapse plugin adds the appropriate classes that we use to style each element. These classes
                  control the overall appearance, as well as the showing and hiding via CSS transitions. You can
                  modify any of this with custom CSS or overriding our default variables.
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Accordion Item #2
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element.
                  These classes control the overall appearance,
                  as well as the showing and hiding via CSS transitions.
                  You can modify any of this with custom CSS or overriding our default variables.
                  It's also worth noting that just about any HTML
                  can go within the <code>.accordion-body</code>,
                  though the transition does limit overflow.
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  Accordion Item #3
                </button>
              </h2>
              <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <strong>This is the third item's accordion body.</strong> It is hidden by default,
                  until the collapse plugin adds the appropriate classes that we use to style each element.
                  These classes control the overall appearance,
                  as well as the showing and hiding via CSS transitions.
                  You can modify any of this with custom CSS or overriding our default variables.
                  It's also worth noting that just about any HTML can go within the
                  <code>.accordion-body</code>,
                  though the transition does limit overflow.
                </div>
              </div>
            </div>
          </div>
        </div>
      <div class="col-3"></div>
      </div>



{% endblock%}

templates/catalog/author_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="container text-start">
        <div class="row my-2">
            <h1>Name of author - "{{ author.first_name }}"</h1>
        </div>
        <div class="row my-2">
            <h1>Last name of author - "{{ author.last_name }}"</h1>
        </div>
<!--        <div class="row my-2">-->
<!--            <p><strong>Author</strong></p>-->
<!--                {% for author in book.author.all %}-->
<!--                    <a href="">{{ author.first_name }} {{ author.last_name }}</a>-->
<!--                {% endfor %}-->
<!--        </div>-->
        <img src="{{ author.photo.url }}" alt="connect" style="max-height: 200px">
        <a href="{{ author.photo.url }}" class="btn btn-primary" target="_blank">Show</a>
        <div class="row my-2">
            <div class="col">
                <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
            </div>
        </div>
        <div class="row my-2">
            <p><strong>About:</strong> {{ author.about }}</p>
        </div>
    </div>
{% endblock %}

templates/catalog/author_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <h4>List if authors</h4>
    {% if author_list %}
        <table class="table table-striped table-bordered text-start">
            <thead>
                <th>Author</th>
                <th>Photo</th>
                <th>Show photo</th>
            </thead>
            <tbody>
                {% for author in author_list.all %}
                <tr>
                    <td><a href="{{author.id}}">{{author.first_name}}</a></td>
                    <td><img src="{{author.photo.url}}" alt="connect" style="max-height: 100px"></td>
                    <td><a href="{{author.photo.url}}" class="btn btn-primary" target="_blank">Show</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No authors in bd</p>
    {% endif %}
{% endblock %}

templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script defer src="/static/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="container-fluid р-1 bg-primary text-white text-center">
        <div class="row">
            <div class="col-2 text-start">
                <img src="{% static 'images/lego-model.jpg' %}" width="70" height="70">
            </div>
            <div class="col-10 ">
                <h3>World of books - printed and digital books</h3>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row bg-warning text-center">
            <h6>
                <a href="{% url 'index' %}">Main page</a>
                <a href="{% url 'about' %}">About company</a>
                <a href="{% url 'contact' %}">Contacts</a>
            </h6>

        </div>
    </div>
    <div class="container-fluid">
        <div class="row text-center text-primary fs-1 fw-bold">
            <div>
                {% block header %} {% endblock header %}
            </div>
        </div>
        <div class="row text-start text-body">
            <div class="col-2">
                {% block sidebar %}
                <nav class="nav flex-column">
                    <a class="nav-link" href="{% url 'books' %}">All books</a>
                    <a class="nav-link" href="{% url 'authors-list' %}">All authors</a>
                </nav>
                {% endblock sidebar %}
            </div>
            <div class="col-10">
                <div class="row text-center">
                    {% block content %}
                    {% endblock content %}
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.paginator.num_pages > 1 %}
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; First</a>
                                    <a href="?page={{ page_obj.previous_page_number }}"> Previous </a>
                                {% endif %}

                                <span class="current">
                                    Page: {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}.
                                </span>

                                {% if page_obj.has_next %}
                                    <a href="?page= {{ page_obj.next_page_number }}">NExt</a>
                                    <a href="?page= {{ page_obj.paginator.num_pages }}">Previous &raquo;</a>
                                {% endif %}
                            {% endif %}
                        </span>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row bg-info text-center text-dark small lh-sm pt-2">
            {% block footer %}
                <p>Copyright IP "Tsokalov Artem", 2025.</p>
            {% endblock footer %}
        </div>

    </div>
</body>
</html>

templates/catalog/book_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="container text-start">
        <div class="row my-2">
            <h1>Name of book - "{{ book.title }}"</h1>
        </div>
        <div class="row my-2">
            <p><strong>Author</strong></p>
                {% for author in book.author.all %}
                    <a href="/authors/{{author.id}}">{{ author.first_name }} {{ author.last_name }}</a>
                {% endfor %}
        </div>
        <img src="{{ book.photo.url }}" alt="connect" style="max-height: 200px">
        <a href="{{ book.photo.url }}" class="btn btn-primary" target="_blank">Show</a>
        <div class="row my-2">
            <div class="col">
                <p><strong>Cost:</strong> {{ book.price }}</p>
            </div>
        </div>
        <div class="row my-2">
            <p><strong>Annotation:</strong> {{ book.summary }}</p>
        </div>
        <div class="row my-2">
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Genre:</strong> {{ book.genre }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Language:</strong> {{ book.language }}</p>
            </div>
            <div class="col mx-2 bg-primary text-white">
                <p><strong>Publisher:</strong> {{ book.publisher }}</p>
            </div>
        </div>
        <div style="margin-left: 20px; margin-top: 10px">
            <h4>Number of templates in bd</h4>
            {% for copy in book.bookinstance_set.all %}
            <hr>
                <p class="text-muted">
                    <strong>Inventory number:</strong> {{ copy.id }}
                </p>
                <p class="text-success">
                    <strong>Status:</strong> {{ copy.status }}
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/catalog/book_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <div class="row text-center text-dark lh-2">
        <h4>List of books from database</h4>
    </div>
    {% if books %}
    <table class="table table-striped table-bordered text-start">
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Genre</th>
                <th>Image</th>
                <th>Show image</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td><a href="{{ book.id }}">{{ book.title }}</a></td>
                    <td>{{ book.display_author }}</td>
                    <td>{{ book.genre }}</td>
                    <td><img src="{{ book.photo.url }}" alt="connect"
                    style="max-height:100px"
                    ></td>
                    <td><a href="{{ book.photo.url }}" class="btn btn-primary"
                    target="_blank">Show</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>database is empty</p>
    {% endif %}
{% endblock %}

templates/catalog/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/catalog/index.html
{% extends "catalog/base.html" %}
{% block title %}World of books{% endblock title%}
{% block header %}
    <h5>{{ text_head }}</h5>
{% endblock header %}
{% block content %}
    <div class="container-fluid my2">
        <div class="row bg-success text-white mx-2">
            <div class="col text-center">
                <p>Welcome to our site <em>World of books</em>. It's very simple site, that is written
                using Django and Bootstrap. Developed by Python like pet project</p>
            </div>
        </div>
        <div class="row text-center text-dark lh-2">
            <h4>Info from database</h4>
        </div>
        <div class="row my-2 text-white">
            <div class="col mx-2 bg-primary">
                Number of books - {{ num_books }}
            </div>
            <div class="col mx-2 bg-primary">
                Available - {{ num_instances }}
            </div>
            <div class="col mx-2 bg-primary">
                Number of authors - {{ num_authors }}
            </div>
        </div>
        <div class="row text-center text-dark lh-2">
                <h3>Books</h3>
        </div>
        {% if num_books > 0 %}
        <div class="row my-2">
            {% for obj in books %}
                <div class="card" style="width: 9rem;">
                    <img src="{{ obj.photo.url }}" class="card-img-top">
                    <div class="card-body">
                        <p class="card-text small">
                            {{ obj.title }}, Price:{{ obj.price }} rub.
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock content %}